#!/usr/bin/env bash
# Android build toolchain for this repo (ADR-0038). Idempotent — safe to re-run.
#
# The build host is .210 (the dev platform). ha-2 does NOT build anything: it has no JDK and no Android
# SDK, exactly as it has no ESP-IDF — it serves artifacts, it does not compile them.
#
# Installs, if missing:
#   - OpenJDK 21 (headless)          apt
#   - Android SDK cmdline-tools      unpacked to $SDK_ROOT/cmdline-tools/latest  (the layout sdkmanager
#                                    requires; unpacking the zip as-is produces the WRONG one)
#   - platform-tools, platform android-35, build-tools 35.0.0
#   - Gradle 8.10.2                  used once to generate the committed wrapper; ./gradlew thereafter
#
# Usage:  app/android/setup-toolchain.sh   then   app/android/build.sh
set -euo pipefail

SDK_ROOT="${ANDROID_SDK_ROOT:-$HOME/android-sdk}"
GRADLE_VERSION="8.10.2"
GRADLE_HOME="$HOME/gradle-dist/gradle-${GRADLE_VERSION}"
CLT_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

say() { printf '\n== %s\n' "$*"; }

# ── JDK ───────────────────────────────────────────────────────────────────────
if ! command -v javac >/dev/null 2>&1; then
  say "installing OpenJDK 21"
  # sudo on .210 wants root's password; instance/.rootpwd is the canonical place to get it.
  if [ -f "$REPO_ROOT/instance/.rootpwd" ]; then
    sudo -S apt-get install -y openjdk-21-jdk-headless unzip < "$REPO_ROOT/instance/.rootpwd"
  else
    sudo apt-get install -y openjdk-21-jdk-headless unzip
  fi
else
  say "JDK present: $(javac -version 2>&1)"
fi

# ── Android SDK ───────────────────────────────────────────────────────────────
if [ ! -x "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
  say "installing Android command-line tools -> $SDK_ROOT"
  mkdir -p "$SDK_ROOT"
  tmp="$(mktemp -d)"
  curl -sSL -o "$tmp/clt.zip" "$CLT_URL"
  unzip -q -o "$tmp/clt.zip" -d "$tmp"
  # The zip contains a top-level cmdline-tools/ directory; sdkmanager insists on
  # <sdk>/cmdline-tools/latest/bin/sdkmanager, so it has to be renamed into place.
  mkdir -p "$SDK_ROOT/cmdline-tools"
  rm -rf "$SDK_ROOT/cmdline-tools/latest"
  mv "$tmp/cmdline-tools" "$SDK_ROOT/cmdline-tools/latest"
  rm -rf "$tmp"
else
  say "Android cmdline-tools present"
fi

say "accepting SDK licenses + installing packages"
yes | "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK_ROOT" --licenses >/dev/null
"$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$SDK_ROOT" \
  "platform-tools" "platforms;android-35" "build-tools;35.0.0" >/dev/null

# ── Gradle (only needed to regenerate the wrapper) ────────────────────────────
if [ ! -x "$GRADLE_HOME/bin/gradle" ] && [ ! -x "$REPO_ROOT/app/android/gradlew" ]; then
  say "installing Gradle ${GRADLE_VERSION} (to generate the wrapper)"
  mkdir -p "$HOME/gradle-dist"
  tmp="$(mktemp -d)"
  curl -sSL -o "$tmp/gradle.zip" "https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
  unzip -q -o "$tmp/gradle.zip" -d "$HOME/gradle-dist"
  rm -rf "$tmp"
fi

# ── local.properties (gitignored, per-host) ───────────────────────────────────
printf '## Generated by setup-toolchain.sh — machine-specific, gitignored.\nsdk.dir=%s\n' \
  "$SDK_ROOT" > "$REPO_ROOT/app/android/local.properties"

say "done. SDK=$SDK_ROOT  JAVA=$(command -v javac)"
echo "Next: app/android/build.sh"
