#!/usr/bin/env python3
"""
Enroll an edge node: mint (or import) its per-device secret, record it in the encrypted server LUT,
and emit that node's `secrets.h` to compile into a per-device firmware (ADR-0010/0011).

Trust model: the server generates the secret, keeps it (encrypted, master = $HA_MASTER_PASSPHRASE),
and bakes the SAME secret into the node's firmware. Physical-presence enrollment — flash via cable from
the G11 (the "scary" path is physical; OTA is break-glass). The per-device firmware means each node has
its own command-signing key + broker credential; revoke = drop it from the LUT + reflash.

  # new node (secret generated)
  HA_MASTER_PASSPHRASE=CHANGE_ME_master_passphrase python3 tools/enroll_node.py --node-id c6-attic \
      --mac 58:e6:c5:11:22:33 --out edge/esp32c6/main/secrets.h

  # rebuild an ALREADY-enrolled node: re-emit a complete, board-correct secrets.h from its existing
  # secret (no re-mint, no server change) — mac/sensor/broker/ota_host come from edge/esp32c6/nodes.yaml
  python3 tools/enroll_node.py --node-id cbed_c6 --from-manifest --reuse --out edge/esp32c6/main/secrets.h

  # import an already-flashed node's existing secret (no reflash)
  HA_MASTER_PASSPHRASE=CHANGE_ME_master_passphrase python3 tools/enroll_node.py --node-id c6-bench \
      --mac AA:BB:CC:00:00:02 --secret <hex> --no-secrets-file

  # print the software confirm token (= SHA256("ha-confirm:"+master)) for the control API
  HA_MASTER_PASSPHRASE=CHANGE_ME_master_passphrase python3 tools/enroll_node.py --show-confirm
"""
import argparse
import re
import secrets as pysecrets
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))       # tools/ — for edge_nodes
from server.control import secret_store as S
import edge_nodes as EN

REPO = Path(__file__).resolve().parents[1]
DEFAULT_LUT = REPO / "instance" / "node_secrets.enc"
DEFAULT_BASE = REPO / "edge" / "esp32c6" / "main" / "secrets.h"


def _define(text: str, name: str, default: str = "") -> str:
    m = re.search(rf'#define\s+{name}\s+"([^"]*)"', text)
    return m.group(1) if m else default


def gen_secrets_h(node_id, cmd_secret, mqtt_pass, ssid, psk, broker, ntp,
                  sensor=None, ota_host=None) -> str:
    # Sensor select (compile-time) lives right under the node id so the board wiring reads as a unit.
    define = EN.sensor_define(sensor) if sensor else None   # SGP40 = firmware default -> no #define
    sensor_line = (define + "\n") if define else ""
    ota_line = f'#define HA_OTA_HOST     "{ota_host}"\n' if ota_host else ""
    return (f"// GIT-IGNORED — generated by enroll_node.py for {node_id}. Do not commit.\n"
            f"#pragma once\n\n"
            f'#define HA_WIFI_SSID    "{ssid}"\n'
            f'#define HA_WIFI_PSK     "{psk}"\n'
            f'#define HA_BROKER_URI   "{broker}"\n'
            f'#define HA_NODE_ID      "{node_id}"\n'
            f"{sensor_line}"
            f'#define HA_NTP_SERVER   "{ntp}"\n'
            f'#define HA_CMD_SECRET   "{cmd_secret}"\n'
            f'#define HA_MQTT_USER    "{node_id}"\n'
            f'#define HA_MQTT_PASS    "{mqtt_pass}"\n'
            f"{ota_line}")


def main() -> None:
    p = argparse.ArgumentParser(description="Enroll an edge node (per-device secret + LUT + secrets.h)")
    p.add_argument("--node-id")
    p.add_argument("--mac", default="", help="chip eFuse MAC (esptool read_mac) — recorded in the LUT")
    p.add_argument("--secret", help="import an existing cmd secret instead of generating one")
    p.add_argument("--mqtt-pass", help="import an existing broker password instead of generating one")
    p.add_argument("--master", help="master passphrase (else $HA_MASTER_PASSPHRASE / instance/.master_pass)")
    p.add_argument("--lut", default=DEFAULT_LUT, type=Path)
    p.add_argument("--base-secrets", default=DEFAULT_BASE, type=Path, help="source of wifi/broker/ntp")
    p.add_argument("--out", type=Path, help="write the generated secrets.h here")
    p.add_argument("--no-secrets-file", action="store_true", help="record in LUT only; don't emit secrets.h")
    p.add_argument("--rotate", action="store_true", help="allow re-enrolling an existing node (new secret)")
    p.add_argument("--reuse", action="store_true",
                   help="re-emit an already-enrolled node's secrets.h from its EXISTING secret "
                        "(no mint, no LUT write) — the rebuild-this-node path")
    p.add_argument("--sensor", choices=EN.SENSORS,
                   help="gas chip -> secrets.h HA_GAS_SGP30 select (else taken from --from-manifest)")
    p.add_argument("--ota-host", help="OTA HTTP host to pin in secrets.h (else from --from-manifest)")
    p.add_argument("--from-manifest", action="store_true",
                   help="pull mac/sensor/broker/ota_host from the board's nodes.yaml for this node")
    p.add_argument("--manifest", type=Path,
                   help="explicit nodes.yaml (else <board>/nodes.yaml next to --out, else the c6 default)")
    p.add_argument("--show-confirm", action="store_true", help="just print the confirm token and exit")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--stamp", default=None, help="ISO created timestamp (else now)")
    a = p.parse_args()

    master = S.load_master(a.master)
    if a.show_confirm:
        print(S.confirm_token(master))
        return
    if not a.node_id:
        sys.exit("--node-id required (or use --show-confirm)")

    lut = S.load_lut(a.lut, master)
    enrolled = a.node_id in lut

    # The manifest supplies board wiring (mac/sensor/broker/ota_host) so the emit needs no hand-editing.
    # Board-aware: use --manifest, else the nodes.yaml next to --out's board, else the c6 default.
    man = {}
    if a.from_manifest:
        man_path = a.manifest or (a.out.parent.parent / "nodes.yaml" if a.out else EN.DEFAULT_MANIFEST)
        man = EN.get(a.node_id, man_path)
    mac = (a.mac or man.get("mac", "")).upper()
    sensor = a.sensor or man.get("sensor")
    ota_host = a.ota_host or man.get("ota_host")

    if a.reuse:
        if not enrolled:
            sys.exit(f"--reuse: {a.node_id!r} is not enrolled yet — enroll it first (drop --reuse)")
        cmd_secret = lut[a.node_id]["cmd_secret"]      # re-emit the SAME secret: server stays in sync
        mqtt_pass = lut[a.node_id]["mqtt_pass"]
    else:
        if enrolled and not a.rotate:
            sys.exit(f"'{a.node_id}' already enrolled — use --reuse to re-emit its secret, "
                     f"or --rotate to re-mint (then reflash that node)")
        cmd_secret = a.secret or pysecrets.token_hex(32)
        mqtt_pass = a.mqtt_pass or pysecrets.token_urlsafe(18)
    stamp = a.stamp or datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    base = a.base_secrets.read_text() if a.base_secrets.exists() else ""
    ssid = _define(base, "HA_WIFI_SSID"); psk = _define(base, "HA_WIFI_PSK")
    broker = man.get("broker") or _define(base, "HA_BROKER_URI", "mqtt://192.168.0.245:1883")
    ntp = _define(base, "HA_NTP_SERVER", "pool.ntp.org")

    action = "reuse" if a.reuse else ("rotate" if enrolled else "enroll")
    secret_src = "existing" if a.reuse else ("imported" if a.secret else "generated")
    print(f"{action} {a.node_id} mac={mac or '?'} sensor={sensor or '?'} secret={secret_src}")
    if a.dry_run:
        print("  [dry-run] LUT + secrets.h not written")
        return

    if a.reuse:
        print("  reusing existing secret from LUT (no LUT write)")
    else:
        lut[a.node_id] = {"mac": mac, "cmd_secret": cmd_secret, "mqtt_user": a.node_id,
                          "mqtt_pass": mqtt_pass, "created": stamp}
        S.save_lut(a.lut, master, lut)
        print(f"  recorded in encrypted LUT: {a.lut}  ({len(lut)} node(s))")

    if not a.no_secrets_file:
        sh = gen_secrets_h(a.node_id, cmd_secret, mqtt_pass, ssid, psk, broker, ntp,
                           sensor=sensor, ota_host=ota_host)
        if a.out:
            a.out.write_text(sh)
            print(f"  wrote {a.out}  → build + CABLE-flash this node (from the G11; OTA is break-glass)")
            # PROJECT_VER identity: IDF reads <project>/version.txt into app_desc.version. Brand it
            # "<node_id>@<fw>" so the OTA node-id gate (ha_ota.c) can refuse a mis-targeted image.
            proj = a.out.parent.parent                        # a.out = <proj>/main/secrets.h
            mqttc = proj / "main" / "ha_mqtt.c"
            fw = _define(mqttc.read_text(), "HA_FW_VERSION", "dev") if mqttc.exists() else "dev"
            (proj / "version.txt").write_text(f"{a.node_id}@{fw}\n")
            print(f"  wrote {proj/'version.txt'} = {a.node_id}@{fw}  (app_desc identity for the OTA gate)")
        else:
            print("  --- secrets.h (write to the node's main/secrets.h) ---\n" + sh)


if __name__ == "__main__":
    main()
